pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'git clone https://github.com/itsAkshayDubey/spring-boot-with-standalone-tomcat.git'
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deliver') {
            steps {
                sh 'cp -f target/spring-boot-with-standalone-tomcat.war /tomcat/webapps/spring-boot-with-standalone-tomcat.war'
            }
        }
        stage('Complete') {
            steps {
                sh "echo 'Done!'"
            }
        }
    }
}